# Generated by Django 5.2.6 on 2025-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_post_author_post_date_alter_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
